# Generated by Django 5.2 on 2025-09-17 22:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='device uuid'),
        ),
    ]
