# Generated by Django 5.2 on 2025-09-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in days'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
